/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_sustech_dbgroup_GPU_GPUNativeLib */

#ifndef _Included_cn_edu_sustech_dbgroup_GPU_GPUNativeLib
#define _Included_cn_edu_sustech_dbgroup_GPU_GPUNativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_sustech_dbgroup_GPU_GPUNativeLib
 * Method:    calculateArrayComplexSum
 * Signature: ([J)D
 */
JNIEXPORT jdouble JNICALL Java_cn_edu_sustech_dbgroup_GPU_GPUNativeLib_calculateArrayComplexSum
  (JNIEnv *, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
